#!/bin/sh


# location of the instalation target directories
ETCDIR="/etc"
CONFDIR="$ETCDIR/hp-spectre-x360"



cd "$CONFDIR"/laptop-mode
#ln -s ../script.d/template.sh 00-template 
ln -s ../script.d/touchpad.sh 01-touchpad 
ln -s ../script.d/flipscreen.sh 02-flipscreen 

echo "DEBUG: make softlinks for tablet mode"
cd "$CONFDIR"/tablet-mode
#ln -s ../script.d/template.sh 00-template 
ln -s ../script.d/touchpad.sh 01-touchpad 
ln -s ../script.d/flipscreen.sh 02-flipscreen 

